name: Build and Upload Container

permissions:
  contents: read
  packages: read

on:
  push:
    branches: [ main ]
    paths:
      - "containers/**"
      - ".github/workflows/build_and_upload_docker_image.yml"
  pull_request:
    paths:
      - "containers/**"
      - ".github/workflows/build_and_upload_docker_image.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildAndPush:
    uses: dandi-cache/dandi-cache-utils/.github/workflows/cache-image.yml@main
    secrets: inherit
